### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by shujaatak** [rcaltin/Secure-Media-Player#1]
Getting the following and similar other errors while building Secure-Media-Player against Qt5.13.2-msvc2017-64bit on windows 10 using vlc-3.0.5-win64 also tried the latest vlc-3.0.8-win64.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E0090	function returning function is not allowed	MediaPlayer	C:\Secure-Media-Player\vlc-3.0.5-win64\sdk\include\vlc\libvlc_media.h	368	
```
Can you please mention your environment on which this project successfully built? which version of Qt, VLC and MSVC did you use whether they were 32bit or 64bit if it matters?

**Comment by rcaltin** [comment]
define VLC_DIR environment variable to point your vlc installation first and make sure your installation contains sdk folder. I built with vlc 3.0.6 x64 but in my opinion it should work with never versions too. 

You can find old vlc archives here : https://download.videolan.org/pub/videolan/vlc/3.0.6/win64/
